#!/bin/bash

#loon kalendri korrektse vorminguga

echo -n "Täna on  "
echo `date +"%A, %B %d, %Y"`

#esimese osa kirjutan l2bi echo, et harjutada, tegelikult pole echo k2sku vaja

#esimese osa lahendus on ka: date +"Täna on %A, %B %d, %Y"

date +"Kell on %H:%M"

echo

#lihtsalt echo lisab tyhja rea

cal

#date annab sulle kuup2eva, mida saad ise vormistada, cal annab kalendri
#man date annab k2su manuaali
